language: objective-c

env:
    - BEFORE_INSTALL=beacon-wallet-iphone/bin/travis/before_install.sh SCRIPT=beacon-wallet-iphone/bin/travis/script.sh

before_install:
    - $BEFORE_INSTALL

script: 
    - $SCRIPT
